### ISSUE TITLE
spread_draws() failure

### ISSUE THREAD

**Issue by srnwbr** [mjskay/tidybayes.rethinking#18] opened 2024-02-29 22:01 UTC
When I run the example from https://mjskay.github.io/tidybayes.rethinking/articles/tidy-rethinking.html, I recieve the following error (below). I get something similar with some of my ulam models when attempting to use add_predicted_draws()

Is this some issue with my rethinking/stan/rstan install? Am I not specifying something with my stan slot?

platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          2.1                         
year           2022                        
month          06                          
day            23                          
svn rev        82513                       
language       R                           
version.string R version 4.2.1 (2022-06-23)
nickname       Funny-Looking Kid    

```
library(magrittr)
library(dplyr)
library(purrr)
library(forcats)
library(tidyr)
library(modelr)
library(tidybayes)
library(tidybayes.rethinking)
library(ggplot2)
library(cowplot)
library(rstan)
library(rethinking)
library(ggrepel)
library(RColorBrewer)
library(gganimate)

theme_set(theme_tidybayes() + panel_border())

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())


set.seed(5)
n = 10
n_condition = 5
ABC =
  tibble(
    condition = factor(rep(c("A","B","C","D","E"), n)),
    response = rnorm(n * 5, c(0,1,2,1,-1), 0.5)
  )

ABC %>%
  ggplot(aes(y = fct_rev(condition), x = response)) +
  geom_point()


m = ulam(alist(
  response ~ normal(mu, sigma),

  mu <- intercept[condition],
  intercept[condition] ~ normal(mu_condition, tau_condition),
  mu_condition ~ normal(0, 5),
  tau_condition ~ exponential(1),
  

  log(sigma) <- sigma_intercept[condition],
  sigma_intercept[condition] ~ normal(0, 1)
), 
data = ABC,
chains = 4,
cores = parallel::detectCores(),
iter = 2000
)


str(rethinking::extract.samples(m))

m %>%
  spread_draws(intercept[condition]) %>%
  head(10)
```

```
Error in tidy_draws(model@stanfit, ...) : 
  no slot of name "stanfit" for this object of class "ulam"
```

**Comment by mjskay** [comment] 2024-03-01 18:40
Looks like this is caused by the new use of the cmdstan backend in rethinking. Should be fixed on master now.

**Closed as completed** 2024-03-01 18:39 UTC
